groups:
  - name: hrflow_alerts
    rules:
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage (instance {{ $labels.instance }})"
          description: "Memory usage is above 85% for 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage (instance {{ $labels.instance }})"
          description: "CPU usage is above 80% for 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Disk Usage (instance {{ $labels.instance }})"
          description: "Disk usage is above 85% for 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend is down (instance {{ $labels.instance }})"
          description: "Backend has been down for more than 1 minute.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: PostgresDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down (instance {{ $labels.instance }})"
          description: "PostgreSQL has been down for more than 1 minute.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down (instance {{ $labels.instance }})"
          description: "Redis has been down for more than 1 minute.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}" 