name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Type check
        working-directory: ./frontend
        run: npm run typecheck || echo "Type check failed but continuing"

      - name: Lint
        working-directory: ./frontend
        run: npm run lint || echo "Linting failed but continuing"

      - name: Create .env.local file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=http://localhost:3001/api" > .env.local

      - name: Build
        working-directory: ./frontend
        run: npm run build 